# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e7019f726863ccae45d88d4c6c2c679f756dce6aa8d0606c834a08a2cdbd3440c99b06428cf4d007e5054162e9cca3d40aa088df6c96c9cefd4c594e4d8cfac2

test:
  secret_key_base: 23d25dde023d3c5d8ff6234e5ba941cbe15570bc5bf529b832fe1d9803c230492de596a99a2f1b709c3685c8a7132385c995dc1ab2d18b2f71876410845172f9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
